name: bookify
description: bookify


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  # extended_sliver: ^2.0.1
  flutter_rating_bar: ^4.0.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  carousel_slider: ^4.0.0
  jiffy: ^4.1.0
  equatable: ^2.0.3
  image_picker: ^0.8.4+3
  flutter_bloc:
  http: ^0.13.4
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.15
  provider: ^5.0.0
  mime: ^1.0.1
  google_maps_flutter: ^2.1.1
  intl: ^0.17.0
  geolocator: ^8.0.0
  firebase_messaging: ^11.2.5
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  flutter_local_notifications: ^9.0.0
  rxdart: ^0.27.3
  file_picker: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/home/
    - assets/tab/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 200
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

